### ISSUE TITLE
Unable to run PullEnvironments function

### ISSUE THREAD

**Issue by PaulSells** [Microsoft/Partner-Smart-Office#53] opened 2018-09-03 11:16 UTC
When attempting to run the PullEnvironments function manually the following error is displayed and the function fails to start.

Error:
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: The host.json file is missing the required 'version' property. See https://aka.ms/functions-hostjson for steps to migrate the configuration file. 
Session Id: xxxxxxxxxxxxxxxxxxxxxxx
Timestamp: 2018-09-03T11:15:23.899Z

**Comment by isaiahwilliams** [comment] 2018-09-04 12:48
Hi @PaulSells and @ManuInNZ,

These issues are caused by the recent changes to the Azure functions runtime. To get a better understanding of what has changed, I would recommend you read [this](https://github.com/Azure/app-service-announcements/issues/129). Adding the version to the host.json does solve one problem, however, the changes in the runtime caused two additional issues. I am almost done with a PR that will resolve all the known issues. My hope is to have it merged today, if possible.

**Comment by ManuInNZ** [comment] 2018-09-06 06:15
I did but that might be due to using the functions version setting and for
now the functions don't restart properly.
I did set the functions as rw to be able to force a run and failed to get a
successful run so far.

**Comment by PaulSells** [comment] 2018-09-06 08:29
Thanks Isiah, have synched the update, will let you know if it runs successfully today

**Comment by PaulSells** [comment] 2018-09-06 10:19
Looks like sync is working again. Now have secure score data up to 05/09/18 however security alert data is still out of date

**Comment by isaiahwilliams** [comment] 2018-09-07 13:54
Hi @PaulSells, I have identified some changes in the Microsoft Security Graph API. Those changes were prevent the synchronization from happening correctly. Since that portion of the API is still considered beta these type of changes are to be expected. If you are interested you can learn more about the changes [here](https://github.com/microsoftgraph/aspnet-security-api-sample). I will be introducing some new testing in the coming days to help me identify these type of issues before they impact you. Please let me know if you have any other issues.

**Comment by ManuInNZ** [comment] 2018-09-07 23:11
I redeployed to a complete new function app and I do have issue with the
security alert.

Looking into the end to end transaction confirms the link to the model
change for the alerts as far as I can see.
The call to the /beta/alerts seems to be running fine even if with a 206
return code but then the exception is raised while processing the returned
JSON

Exception while executing function: ProcessSecurity Exception binding
> parameter 'alerts' Unexpected character encountered while parsing value: [.
> Path 'value[0].comments', line 1, position 369.


I have observed the same error since more than a week now.

Cheers
Manu

Le sam. 8 sept. 2018 à 01:54, Isaiah Williams <notifications@github.com> a
écrit :

**Comment by isaiahwilliams** [comment] 2018-09-07 23:35
HI @ManuInNZ, thank you for sharing that information. I was able to identify the issue and I just merge PR #58 that has fix for this issue. Can you update your instance and test again please?

**Comment by ManuInNZ** [comment] 2018-09-08 01:27
Hi Isaiah

Synched and tested including with the latest Enum fix.

No issues so far on that one anymore.
Now issues on Utilisation but maybe due to the date change and absence of
data for the day. I get a 204 return code from the PC API call.

Thank you Isaiah

**Comment by isaiahwilliams** [comment] 2018-09-08 15:49
I am going to close this issue because both issues have been resolved. I appreciate all the help with resolving these issues.

**Closed by isaiahwilliams** 2018-09-08 15:49 UTC
Labels: bug, help wanted
