### ISSUE TITLE
No Reply Address is registered for the application

### ISSUE THREAD

**Issue by ntaylor0909** [microsoft/Partner-Smart-Office#77] opened 2019-05-17 01:03 UTC
# Steps to reproduce

I deployed the solution using the Deployment script and I ran into this error.

## Expected behavior

I expected to be able to log in.

## Actual behavior

It fails on re-directing back from the Azure AD authentication. I've tried putting a couple different Reply URLs into the Azure AD Application settings but it still won't let me log in. I'm not sure where to find the correct Reply URL in the App Service.

![image](https://user-images.githubusercontent.com/10465536/57896231-f234d480-780c-11e9-99c0-6ae9e02d1ef2.png)

**Comment by Trafalger1** [comment] 2019-05-20 12:15
I have this exact same issue, if anyone figures it out let me know.  I've tried every combination of reply URL i could think of.

**Comment by isaiahwilliams** [comment] 2019-05-20 21:37
Hi @ntaylor0909, 

You are encountering this issue because the Azure AD application you are using for authentication has not been added as a reply address. You can solve this problem through the [Azure management](https://portal.azure.com) by performing the following 

1. Authenticate using credentials that have global admin privileges
2. Click on Azure Active Directory (by default you can find this on the navigation bar on the lower left)
3. Click App registrations
4. Click on the application you created for this deployment 
5. Click authentication and add https://yoursite.azurewebsites.net/signin-oidc
6. Click save to commit the changes

I will review the deployment documentation to see if I can identify the root cause for this.

**Comment by Trafalger1** [comment] 2019-05-20 21:46
Thank you for the suggestion @isaiahwilliams however the issue persists :(

**Comment by isaiahwilliams** [comment] 2019-05-20 21:48
Hi @Trafalger1, 

Just to confirm did you modify the value of the redirect URI you added to match your deployment? (e.g. if your website is partnersecurescore.azurewebsites.net the address would be https://partnersecurescore.azurewebsites.net/signin-oidc)

**Comment by Trafalger1** [comment] 2019-05-20 21:49
Yes i did...

**Comment by Trafalger1** [comment] 2019-05-20 21:50
If you'd like i can private email you our web app address @isaiahwilliams

**Comment by Trafalger1** [comment] 2019-05-21 01:36
I have tried about a dozen different URLs with no luck.
@isaiahwilliams

**Comment by isaiahwilliams** [comment] 2019-05-21 01:42
@Trafalger1 are you getting the same error that was originally reported?


Isaiah Williams
________________________________

**Comment by Trafalger1** [comment] 2019-05-21 01:42
yes exactly the same....

**Comment by Trafalger1** [comment] 2019-05-21 01:46
sends me to this URL when you try and login..

https://login.microsoftonline.com/common/oauth2/authorize?client_id=268a2edf-d030xxxxxxxxxxxxxxxxxx..etc

**Comment by isaiahwilliams** [comment] 2019-05-21 01:49
@Trafalger1 since you have added a redirect URI and you are still getting this error, it makes me think the portal is using a different application for authentication than the one that has been updated. To confirm this can you confirm the application identifier for the application you are updating matches the the value for the Authentication:ClientId setting found on the web app?

Isaiah Williams
________________________________

**Comment by Trafalger1** [comment] 2019-05-21 01:50
Sure where would I look to confirm that?

**Comment by isaiahwilliams** [comment] 2019-05-21 01:54
The Authentication:ClientId value is under the configuration section for the Azure App Service. The identifier of the Azure AD application is found in the overview section for the application list under the app registration section.

Isaiah Williams
________________________________

**Comment by Trafalger1** [comment] 2019-05-21 01:57
The app ID from the error message and the app ID of the app with the reply URL are identical if thats what your asking.

**Comment by isaiahwilliams** [comment] 2019-05-21 02:00
Okay that is good to know, it sounds like there might be a bug with the Azure management portal. Can you try using the App registration (legacy) feature to confirm the reply URL is set as described above? If it can you delete the reply URL entry, save, add it back, and finally save it.

Isaiah Williams
________________________________

**Comment by Trafalger1** [comment] 2019-05-21 02:03
![image](https://user-images.githubusercontent.com/50831827/58063162-12d19700-7b4b-11e9-95a2-6f1c3a48f59f.png)

**Comment by Trafalger1** [comment] 2019-05-21 02:04
![image](https://user-images.githubusercontent.com/50831827/58063196-3399ec80-7b4b-11e9-8ae0-fca657368e28.png)

**Comment by Trafalger1** [comment] 2019-05-21 02:05
no joy @isaiahwilliams

**Comment by isaiahwilliams** [comment] 2019-05-21 02:13
Thank you for sharing that, you are getting a different error than what ntaylor0909 reported.  The original error stated a reply URL was not present. Your error is because of mismatch. Since the expected value is not working, the quickest solution would be browse to your site. When you are redirect to the login.microsoftonline.com page, do not enter your credentials. Instead copy the address into Notepad, then extract the redirect_url value from the address. It will be URL encoded, that value decoded is what the reply URL should be.

In my environment it is https://partnertest.azurewebsites.net/signin-oidc. So, it will be interesting to see what you find.

Isaiah Williams
________________________________

**Comment by Trafalger1** [comment] 2019-05-21 02:15
Interesting ...

redirect_uri=http%3A%2F%2Fmyurlapp.azurewebsites.net%2Fsignin-oidc

**Comment by Trafalger1** [comment] 2019-05-21 02:18
it worked...the redirect URL needed to be http NOT https:

i am in now i need to set it up for my CSP....

thank you for the help.  I wonder why this isn't https tho..but at least for now I can test it out.

**Comment by isaiahwilliams** [comment] 2019-05-21 02:19
Good catch, I will update the template in the future to force HTTPS. Glad you got it working!

Isaiah Williams
________________________________

**Comment by Trafalger1** [comment] 2019-05-21 02:22
Is it possible to force it to https after it's been deployed?  or will that require a redeploy?

**Comment by isaiahwilliams** [comment] 2019-05-21 02:28
Yes, there is an option in the configurations for the instance of Azure App Services. You can find details about this at https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-ssl#enforce-https

Isaiah Williams
________________________________

**Comment by ntaylor0909** [comment] 2019-05-21 02:57
Thanks for the help. It looks like this was answered in this FAQ as well: https://github.com/Microsoft/Partner-Smart-Office/wiki/FAQ#why-do-i-receive-an-access-denied-message-when-attempting-to-access-the-portal

**Closed** 2020-07-09 16:16 UTC
